import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Editor from "@monaco-editor/react";
import {
  Play,
  RefreshCw,
  FileCode,
  Folder,
  FolderOpen,
  Cpu,
  Radio,
  Link2,
  Check,
  Trash2,
  TerminalSquare,
  MoreHorizontal,
  Box,
} from "lucide-react";
import { Button, IconButton } from "@/components/ui/Button";
import { Badge, StatusDot } from "@/components/ui/Badge";
import { Switch } from "@/components/ui/Form";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";
import { useDesignStore } from "@/store/useDesignStore";

const FILES = ["falcon17.py", "couplers.py", "readout.py"];

const CODE = `"""Falcon-17 — 17-qubit heavy-hex processor.

Auto-generated by QRIVARA · bidirectional sync with the Visual Designer.
Built with Qiskit Metal (qiskit-community/qiskit-metal).
"""
from qiskit_metal import designs, MetalGUI, Dict
from qiskit_metal.qlibrary.qubits.transmon_pocket import TransmonPocket
from qiskit_metal.qlibrary.tlines.meandered import RouteMeander
from qiskit_metal.qlibrary.couplers.coupled_line_tee import CoupledLineTee
from qiskit_metal.qlibrary.couplers.tunable_coupler_01 import TunableCoupler01
from qiskit_metal.qlibrary.terminations.launchpad_wb import LaunchpadWirebond
from qiskit_metal.analyses.quantization import LOManalysis

# --- design canvas -------------------------------------------------------
design = designs.DesignPlanar()
design.chips.main.size.size_x = "9mm"
design.chips.main.size.size_y = "9mm"
design.overwrite_enabled = True

QUBIT_FREQS = [5.21, 4.98, 5.34, 5.07, 5.19, 4.92, 5.28, 5.11, 5.02]

def add_qubit(name, x, y):
    return TransmonPocket(design, name, options=Dict(
        pos_x=f"{x}mm", pos_y=f"{y}mm",
        pad_gap="30um", pad_width="455um", pad_height="90um",
        connection_pads=Dict(
            readout=Dict(loc_W=+1, loc_H=+1, pad_width="80um", pad_gap="50um"),
            bus_a=Dict(loc_W=-1, loc_H=+1, pad_width="70um"),
            bus_b=Dict(loc_W=-1, loc_H=-1, pad_width="70um"),
        ),
        hfss_inductance="11nH",
    ))

# --- heavy-hex lattice ---------------------------------------------------
qubits = []
for i, f in enumerate(QUBIT_FREQS):
    col, row = i % 3, i // 3
    qubits.append(add_qubit(f"Q{i+1}", -2.4 + col * 2.4, -2.4 + row * 2.4))

# CPW feedline IO (wirebond launch pads)
LaunchpadWirebond(design, "LP_in",  options=Dict(pos_x="-4mm", pos_y="0mm"))
LaunchpadWirebond(design, "LP_out", options=Dict(pos_x="4mm",  pos_y="0mm",
                                                  orientation="180"))

# λ/4 readout resonators (RouteMeander) tap-coupled via CoupledLineTee
for i, q in enumerate(qubits):
    CoupledLineTee(design, f"tee{i+1}", options=Dict(
        pos_x=f"{-2.0 + (i % 3) * 2.0}mm", pos_y="2.4mm",
        coupling_length="200um", coupling_space="7um",
    ))
    RouteMeander(design, f"R{i+1}", options=Dict(
        total_length="4.2mm", fillet="90um", hfss_wire_bonds=True,
        pin_inputs=Dict(
            start_pin=Dict(component=q.name, pin="readout"),
            end_pin=Dict(component=f"tee{i+1}", pin="second_end"),
        ),
    ))

# flux-tunable coupler between Q1 and Q2
TunableCoupler01(design, "C1", options=Dict(
    pos_x="-1.2mm", pos_y="-2.4mm", c_width="400um",
))

gui = MetalGUI(design)
gui.rebuild()

# --- LOM: capacitance matrix → quantized Hamiltonian ---------------------
lom = LOManalysis(design, "q3d")
lom.sim.setup.max_passes = 12
lom.sim.run(components=["Q7"], open_terminations=[("Q7", "readout")])
lom.setup.junctions = Dict(Lj=11, Cj=2)
lom.run_lom()
print(lom.lumped_oscillator_all)   # f_Q, EC, EJ, anharmonicity, chi, g
`;

type LogKind = "prompt" | "info" | "ok" | "warn";
const BASE_LOG: { k: LogKind; t: string }[] = [
  { k: "prompt", t: ">>> python falcon17.py" },
  { k: "info", t: "[qiskit-metal 0.1.5] initialising DesignPlanar (9mm × 9mm)" },
  { k: "info", t: "[qiskit-metal] instantiated 9 TransmonPocket qubits" },
  { k: "info", t: "  + 9 RouteMeander λ/4 resonators · 9 CoupledLineTee taps" },
  { k: "info", t: "  + 1 TunableCoupler01  g = 92 MHz · 2 LaunchpadWirebond" },
  { k: "info", t: "rebuilding GUI geometry … 312 polygons" },
  { k: "info", t: "LOManalysis(design, 'q3d'): Q3D capacitance extraction" },
  { k: "info", t: "  pass 8/12   ΔC = 0.18%  → converged (96k tets)" },
  { k: "ok", t: "  run_lom(): Q7 f_Q = 5.214 GHz · EC = 242 MHz · EJ = 14.9 GHz" },
  { k: "ok", t: "  anharmonicity = -298 MHz · χ = -0.54 MHz · g = 99 MHz" },
  { k: "ok", t: "✓ Design built · 17 qubits · 312 components · 0 errors" },
];

const OUTLINE = [
  { icon: Cpu, name: "Q1–Q9 · TransmonPocket", tone: "text-primary" },
  { icon: Radio, name: "R1–R9 · RouteMeander", tone: "text-cyan" },
  { icon: Link2, name: "tee1–9 · CoupledLineTee", tone: "text-success" },
  { icon: Link2, name: "C1 · TunableCoupler01", tone: "text-violet" },
];

const TREE = [
  { type: "folder", name: "design", open: true, children: ["falcon17.py", "lattice.py"] },
  { type: "folder", name: "components", open: false, children: ["couplers.py", "readout.py"] },
  { type: "folder", name: "analysis", open: false, children: ["eigenmode.py", "sweep.py"] },
];

export default function CodeStudio() {
  const navigate = useNavigate();
  const [active, setActive] = useState("falcon17.py");
  // Prefer code generated from the Visual Designer (if the user came via "Open in Code Studio")
  const [code] = useState(() => {
    try {
      return sessionStorage.getItem("qrivara:generated") || CODE;
    } catch {
      return CODE;
    }
  });
  const [liveSync, setLiveSync] = useState(true);
  const [running, setRunning] = useState(false);
  const [runDone, setRunDone] = useState(false);
  const [log, setLog] = useState(BASE_LOG);
  const setGraph = useDesignStore((s) => s.setGraph);

  const run = async () => {
    setRunning(true);
    setRunDone(false);
    setLog((l) => [...l, { k: "prompt", t: ">>> executing script on backend sandbox..." }]);
    try {
      const res = await api.executeCode(code);
      if (res.logs) {
        setLog((l) => [...l, ...res.logs]);
      }
      if (res.doc && liveSync) {
        setGraph(res.doc.nodes, res.doc.edges);
      }
      setRunDone(true);
    } catch (err: any) {
      setLog((l) => [...l, { k: "warn", t: `Execution failed: ${err.message}` }]);
    } finally {
      setRunning(false);
    }
  };

  const logColor: Record<LogKind, string> = {
    prompt: "text-primary",
    info: "text-fg-muted",
    ok: "text-success",
    warn: "text-warning",
  };

  return (
    <div className="flex h-full flex-col">
      {/* Top bar */}
      <div className="flex h-12 shrink-0 items-center gap-1 border-b border-line bg-surface/50 px-2">
        {FILES.map((f) => (
          <button
            key={f}
            onClick={() => setActive(f)}
            className={cn(
              "flex items-center gap-2 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors",
              active === f
                ? "bg-surface-3 text-fg"
                : "text-fg-subtle hover:bg-surface-2 hover:text-fg",
            )}
          >
            <FileCode className="h-3.5 w-3.5 text-cyan" />
            {f}
          </button>
        ))}
        <div className="ml-auto flex items-center gap-3">
          <div className="hidden items-center gap-2 rounded-full border border-line bg-surface-2 py-1 pl-2.5 pr-3 sm:flex">
            <RefreshCw className={cn("h-3.5 w-3.5 text-cyan", liveSync && "animate-spin-slow")} />
            <span className="text-2xs font-medium text-fg-muted">
              Canvas ⇄ Code · {liveSync ? "in sync" : "paused"}
            </span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="text-2xs text-fg-subtle">Live sync</span>
            <Switch checked={liveSync} onChange={setLiveSync} />
          </div>
          <Button size="sm" variant="ghost" icon={<Box className="h-3.5 w-3.5" />} onClick={() => navigate("/app/view3d?source=live")}>
            View in 3D
          </Button>
          <Button size="sm" loading={running} icon={<Play className="h-3.5 w-3.5" />} onClick={run}>
            Run
          </Button>
          <IconButton size="sm"><MoreHorizontal className="h-4 w-4" /></IconButton>
        </div>
      </div>

      {/* Middle */}
      <div className="flex min-h-0 flex-1">
        {/* File tree */}
        <aside className="hidden w-56 shrink-0 flex-col border-r border-line bg-surface/40 py-2 md:flex">
          <p className="px-4 pb-1 pt-1 text-2xs font-semibold uppercase tracking-wider text-fg-subtle">
            Explorer
          </p>
          {TREE.map((folder) => (
            <div key={folder.name} className="px-2">
              <div className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs font-medium text-fg-muted">
                {folder.open ? (
                  <FolderOpen className="h-3.5 w-3.5 text-warning" />
                ) : (
                  <Folder className="h-3.5 w-3.5 text-fg-subtle" />
                )}
                {folder.name}
              </div>
              {folder.open &&
                folder.children.map((file) => (
                  <button
                    key={file}
                    onClick={() => FILES.includes(file) && setActive(file)}
                    className={cn(
                      "flex w-full items-center gap-1.5 rounded-lg px-2 py-1.5 pl-7 text-xs transition-colors",
                      active === file
                        ? "bg-primary/12 text-primary"
                        : "text-fg-subtle hover:bg-surface-2 hover:text-fg",
                    )}
                  >
                    <FileCode className="h-3.5 w-3.5" />
                    {file}
                  </button>
                ))}
            </div>
          ))}
        </aside>

        {/* Editor */}
        <div className="flex min-w-0 flex-1 flex-col">
          <div className="flex-1">
            <Editor
              height="100%"
              defaultLanguage="python"
              theme="vs-dark"
              value={code}
              onMount={(_editor, monaco) => {
                monaco.editor.defineTheme("qrivara-dark", {
                  base: "vs-dark",
                  inherit: true,
                  rules: [
                    { token: "comment", foreground: "7C756C", fontStyle: "italic" },
                    { token: "string", foreground: "40C08A" },
                    { token: "keyword", foreground: "B47CF0" },
                    { token: "number", foreground: "E0B255" },
                    { token: "type", foreground: "C8803A" },
                    { token: "function", foreground: "C8803A" },
                  ],
                  colors: {
                    "editor.background": "#161514",
                    "editor.foreground": "#F5F3EF",
                    "editor.lineHighlightBackground": "#1F1D1B",
                    "editorLineNumber.foreground": "#7C756C",
                    "editorLineNumber.activeForeground": "#B2ABA2",
                    "editorGutter.background": "#161514",
                    "editor.selectionBackground": "#C8803A44",
                    "editorCursor.foreground": "#C8803A",
                    "editorIndentGuide.background1": "#2C2926",
                    "editorWidget.background": "#1F1D1B",
                  },
                });
                monaco.editor.setTheme("qrivara-dark");
              }}
              options={{
                fontFamily: "'JetBrains Mono', monospace",
                fontSize: 13,
                fontLigatures: true,
                minimap: { enabled: true },
                scrollBeyondLastLine: false,
                padding: { top: 16 },
                smoothScrolling: true,
                cursorBlinking: "smooth",
                renderLineHighlight: "all",
                lineNumbersMinChars: 3,
                scrollbar: { verticalScrollbarSize: 10, horizontalScrollbarSize: 10 },
              }}
            />
          </div>
        </div>

        {/* Outline / preview */}
        <aside className="hidden w-72 shrink-0 flex-col border-l border-line bg-surface/40 xl:flex">
          <div className="border-b border-line px-4 py-3">
            <h3 className="text-sm font-semibold text-fg">Generated Components</h3>
            <p className="text-2xs text-fg-subtle">Reflected live on the canvas</p>
          </div>
          <div className="flex-1 space-y-1.5 overflow-y-auto p-3">
            {OUTLINE.map((o) => {
              const Icon = o.icon;
              return (
                <div key={o.name} className="flex items-center gap-2.5 rounded-xl border border-line bg-surface-2 p-2.5">
                  <Icon className={cn("h-4 w-4 shrink-0", o.tone)} />
                  <span className="flex-1 text-xs font-medium text-fg">{o.name}</span>
                  <Check className="h-3.5 w-3.5 text-success" />
                </div>
              );
            })}
          </div>
          <div className="border-t border-line p-3">
            <div className="rounded-xl border border-line bg-surface-2 p-3">
              <p className="mb-2 text-2xs font-semibold uppercase tracking-wider text-fg-subtle">
                Design Metrics
              </p>
              {[
                ["Qubits", "17"],
                ["Components", "312"],
                ["Lines of code", "64"],
              ].map(([k, v]) => (
                <div key={k} className="flex items-center justify-between py-1 text-sm">
                  <span className="text-fg-subtle">{k}</span>
                  <span className="font-mono text-fg">{v}</span>
                </div>
              ))}
            </div>
          </div>
        </aside>
      </div>

      {/* Console */}
      <div className="flex h-44 shrink-0 flex-col border-t border-line bg-bg-deep/40">
        <div className="flex h-9 items-center gap-3 border-b border-line px-3">
          <div className="flex items-center gap-1.5 text-xs font-medium text-fg">
            <TerminalSquare className="h-3.5 w-3.5 text-cyan" />
            Output
          </div>
          <span className="text-2xs text-fg-subtle">Problems (0)</span>
          <span className="text-2xs text-fg-subtle">Terminal</span>
          {running && (
            <span className="flex items-center gap-1.5 text-2xs text-cyan">
              <StatusDot tone="cyan" pulse /> running…
            </span>
          )}
          <IconButton size="sm" className="ml-auto" onClick={() => setLog(BASE_LOG)}>
            <Trash2 className="h-3.5 w-3.5" />
          </IconButton>
        </div>
        <div className="flex-1 space-y-0.5 overflow-y-auto p-3 font-mono text-xs">
          {log.map((line, i) => (
            <div key={i} className={logColor[line.k]}>
              {line.t}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
