"""Static read-only catalogs (component library + materials), mirroring the
frontend SSOT. Custom components live in the DB; these are the built-ins."""

COMPONENT_LIBRARY = [
    # Qubits
    {"id": "transmon", "kind": "transmon", "name": "Transmon", "category": "Qubits", "color": "primary",
     "description": "Charge-insensitive qubit (EJ >> EC)",
     "defaults": {"pad_width_um": 455, "pad_height_um": 90, "pad_gap_um": 30, "junction_width_nm": 200,
                  "junction_length_nm": 200, "fillet_radius_um": 10, "halo_gap_um": 40,
                  "target_freq_GHz": 5.2, "anharmonicity_MHz": -310, "material": "Aluminum", "layer": 1}},
    {"id": "xmon", "kind": "transmon", "name": "Xmon", "category": "Qubits", "color": "primary",
     "description": "Cross-shaped transmon with 4 coupling arms",
     "defaults": {"arm_length_um": 180, "arm_width_um": 24, "cross_width_um": 24, "gap_um": 30,
                  "fillet_radius_um": 5, "target_freq_GHz": 5.0, "material": "Aluminum", "layer": 1}},
    {"id": "concentric-transmon", "kind": "transmon", "name": "Concentric Transmon", "category": "Qubits", "color": "primary",
     "description": "Circular center pad with outer ring, low footprint",
     "defaults": {"inner_radius_um": 120, "outer_radius_um": 160, "gap_um": 20, "target_freq_GHz": 4.8}},
    {"id": "fluxonium", "kind": "fluxonium", "name": "Fluxonium", "category": "Qubits", "color": "violet",
     "description": "Junction-array shunted qubit, high anharmonicity",
     "defaults": {"inductor_count": 100, "loop_area_um2": 30, "junction_area_um2": 0.02,
                  "kinetic_inductance_pH": 15, "target_freq_GHz": 0.5}},
    # Resonators
    {"id": "cpw-resonator", "kind": "resonator", "name": "CPW Resonator", "category": "Resonators", "color": "cyan",
     "description": "Coplanar-waveguide resonator",
     "defaults": {"length_um": 4200, "width_um": 10, "gap_um": 6, "fillet_radius_um": 90,
                  "impedance_ohm": 50, "target_freq_GHz": 6.5}},
    {"id": "readout-resonator", "kind": "resonator", "name": "Readout Resonator", "category": "Resonators", "color": "cyan",
     "description": "Dispersive readout resonator",
     "defaults": {"length_um": 4200, "fillet_radius_um": 90, "coupling_MHz": 1.2, "frequency_GHz": 7.1}},
    {"id": "purcell-filter", "kind": "purcell-filter", "name": "Purcell Filter", "category": "Resonators", "color": "cyan",
     "description": "Bandpass filter to prevent qubit decay via readout",
     "defaults": {"bandwidth_MHz": 50, "frequency_GHz": 7.1, "length_um": 2000}},
    # Couplers
    {"id": "capacitive-coupler", "kind": "coupler", "name": "Capacitive Coupler", "category": "Couplers", "color": "violet",
     "description": "Direct capacitive qubit-qubit coupling",
     "defaults": {"distance_um": 12, "coupling_length_um": 120, "capacitance_fF": 4.5}},
    {"id": "inductive-coupler", "kind": "coupler", "name": "Inductive Coupler", "category": "Couplers", "color": "violet",
     "description": "Mutual-inductance coupling element",
     "defaults": {"mutual_inductance_pH": 2.1, "loop_area_um2": 40, "distance_um": 10}},
    {"id": "snail-coupler", "kind": "squid", "name": "SNAIL Coupler", "category": "Couplers", "color": "violet",
     "description": "Asymmetric SQUID for 3-wave mixing and 0-ZZ crosstalk",
     "defaults": {"loop_area_um2": 25, "asymmetry_ratio": 0.1, "target_g_MHz": 100}},
    # Control
    {"id": "drive-line", "kind": "junction", "name": "Drive Line", "category": "Control", "color": "warning",
     "description": "XY microwave drive line",
     "defaults": {"width_um": 10, "gap_um": 6, "impedance_ohm": 50, "power_dBm": -30}},
    {"id": "flux-line", "kind": "flux-line", "name": "Flux Line", "category": "Control", "color": "warning",
     "description": "Z flux-bias control line",
     "defaults": {"current_mA": 1.0, "width_um": 4, "distance_um": 8}},
    # Readout
    {"id": "feedline", "kind": "feedline", "name": "Feedline", "category": "Readout", "color": "success",
     "description": "Shared readout transmission line",
     "defaults": {"length_um": 2800, "width_um": 10, "gap_um": 6, "fillet_radius_um": 90, "impedance_ohm": 50}},
    {"id": "readout-port", "kind": "launchpad", "name": "Readout Port", "category": "Readout", "color": "success",
     "description": "Wirebond IO port for readout",
     "defaults": {"freq_range_GHz": "6-8", "power_dBm": -40}},
    {"id": "jpa", "kind": "parametric-amplifier", "name": "Parametric Amp (JPA)", "category": "Readout", "color": "success",
     "description": "On-chip Josephson Parametric Amplifier for signal boost",
     "defaults": {"gain_dB": 20, "bandwidth_MHz": 20, "center_freq_GHz": 7.1}},
    # Chip
    {"id": "chip-substrate", "kind": "ground", "name": "Chip Substrate", "category": "Chip", "color": "success",
     "description": "Wafer substrate the circuit is patterned on",
     "defaults": {"length_mm": 9, "width_mm": 9, "thickness_um": 525, "material": "Silicon"}},
    {"id": "ground-plane", "kind": "ground", "name": "Ground Plane", "category": "Chip", "color": "success",
     "description": "Patterned ground reference layer",
     "defaults": {"layer": 0, "thickness_nm": 200}},
    {"id": "air-bridge", "kind": "airbridge", "name": "Air Bridges", "category": "Chip", "color": "success",
     "description": "Crossover suppressing slotline modes",
     "defaults": {"length_um": 30, "width_um": 8, "height_um": 3}},
    {"id": "tsv", "kind": "tsv", "name": "Through-Silicon Via", "category": "Chip", "color": "success",
     "description": "Vertical interconnect for 3D routing",
     "defaults": {"diameter_um": 20, "depth_um": 150, "material": "Copper"}},
    # Qubits (more)
    {"id": "tunable-transmon", "kind": "squid", "name": "Tunable Transmon", "category": "Qubits", "color": "primary",
     "description": "SQUID-based frequency-tunable transmon",
     "defaults": {"pad_width_um": 455, "pad_height_um": 90, "pad_gap_um": 30, "squid_loop_um2": 50,
                  "junction_asymmetry": 0.0, "target_freq_GHz": 5.2, "anharmonicity_MHz": -310,
                  "material": "Aluminum", "layer": 1}},
    {"id": "gatemon", "kind": "transmon", "name": "Gatemon", "category": "Qubits", "color": "primary",
     "description": "Voltage-tunable semiconductor-nanowire junction qubit",
     "defaults": {"nanowire_length_nm": 200, "gate_voltage_V": 0.0, "target_freq_GHz": 5.0}},
    # Couplers (more)
    {"id": "tunable-coupler", "kind": "squid", "name": "Tunable Coupler", "category": "Couplers", "color": "violet",
     "description": "Frequency-tunable coupler for in-situ ZZ control",
     "defaults": {"loop_area_um2": 30, "idle_freq_GHz": 8.5, "on_g_MHz": 100, "off_g_MHz": 0.5}},
    {"id": "coupled-line-tee", "kind": "coupler", "name": "Coupled-Line Tee", "category": "Couplers", "color": "violet",
     "description": "Distributed feedline tap to a hanging resonator",
     "defaults": {"coupling_length_um": 150, "coupling_gap_um": 5, "down_length_um": 50}},
    {"id": "jj-array", "kind": "junction", "name": "Josephson Junction Array", "category": "Couplers", "color": "violet",
     "description": "Superinductor / array for fluxonium & high-impedance lines",
     "defaults": {"junction_count": 100, "junction_area_um2": 0.02, "array_L_nH": 200}},
    # Readout / amplification (more)
    {"id": "twpa", "kind": "parametric-amplifier", "name": "TWPA", "category": "Readout", "color": "success",
     "description": "Traveling-wave parametric amplifier, broadband near-quantum-limited gain",
     "defaults": {"gain_dB": 20, "bandwidth_GHz": 3.0, "cells": 2000, "phase_match_GHz": 6.0}},
    {"id": "launchpad", "kind": "launchpad", "name": "Launchpad (Wirebond)", "category": "Readout", "color": "success",
     "description": "Tapered CPW launch to a wirebond pad",
     "defaults": {"pad_width_um": 300, "pad_height_um": 300, "taper_length_um": 300, "impedance_ohm": 50}},
    # Chip / fab features (more)
    {"id": "vacuum-gap-cap", "kind": "ground", "name": "Vacuum-Gap Capacitor", "category": "Chip", "color": "success",
     "description": "Suspended plate capacitor — low dielectric participation",
     "defaults": {"plate_area_um2": 4000, "gap_um": 2, "capacitance_fF": 18}},
    {"id": "bandage", "kind": "airbridge", "name": "Bandage / Crossover", "category": "Chip", "color": "success",
     "description": "Galvanic bandage joining junction leads to pads (loss reduction)",
     "defaults": {"length_um": 12, "width_um": 6, "overlap_um": 3}},
    {"id": "alignment-marker", "kind": "ground", "name": "Alignment Marker", "category": "Chip", "color": "success",
     "description": "E-beam / optical alignment fiducial",
     "defaults": {"size_um": 20, "type": "cross", "layer": 10}},
    {"id": "dicing-lane", "kind": "ground", "name": "Dicing Lane", "category": "Chip", "color": "success",
     "description": "Saw street / keep-out boundary",
     "defaults": {"width_um": 200, "keepout_um": 200}},

    # ── Beyond-transmon / protected qubits (scqubits, Krantz 2019, arXiv:2106.10296) ──
    {"id": "zero-pi", "kind": "fluxonium", "name": "0-π Qubit", "category": "Qubits", "color": "violet",
     "description": "Noise-protected multimode qubit (heavy charge + light flux mode)",
     "defaults": {"EJ_GHz": 10.0, "EC_GHz": 0.02, "EL_GHz": 0.008, "ECS_GHz": 10.0,
                  "flux_ratio": 0.5, "junction_count": 2, "superinductor_L_nH": 200}},
    {"id": "cshunt-flux-qubit", "kind": "fluxonium", "name": "C-Shunt Flux Qubit", "category": "Qubits", "color": "violet",
     "description": "3-junction Mooij loop with a large shunt capacitor (flux qubit)",
     "defaults": {"junction_asymmetry": 0.43, "EJ_GHz": 35.0, "EC_GHz": 0.2,
                  "shunt_cap_fF": 45, "loop_area_um2": 30, "flux_ratio": 0.5}},
    {"id": "bifluxon", "kind": "fluxonium", "name": "Bifluxon", "category": "Qubits", "color": "violet",
     "description": "Parity-protected qubit: superinductor + 2 junctions + a charge island",
     "defaults": {"EJ_GHz": 8.0, "EC_GHz": 1.0, "superinductor_L_nH": 270,
                  "offset_charge_ng": 0.0, "flux_ratio": 0.5}},
    {"id": "cos2phi-qubit", "kind": "fluxonium", "name": "cos(2φ) Qubit", "category": "Qubits", "color": "violet",
     "description": "Parity-protected qubit frustrated at half flux (cos 2φ potential)",
     "defaults": {"EJ_GHz": 15.0, "EC_GHz": 1.0, "EL_GHz": 1.0, "flux_ratio": 0.5}},
    {"id": "floating-transmon", "kind": "transmon", "name": "Floating Transmon (Double-Pad)", "category": "Qubits", "color": "primary",
     "description": "Two-island floating transmon (no galvanic ground tie)",
     "defaults": {"pad_width_um": 450, "pad_height_um": 120, "pad_gap_um": 30, "ground_gap_um": 40,
                  "target_freq_GHz": 5.0, "anharmonicity_MHz": -300, "material": "Aluminum", "layer": 1}},
    {"id": "unimon", "kind": "transmon", "name": "Unimon", "category": "Qubits", "color": "primary",
     "description": "Single-junction qubit embedded in a grounded λ/2 resonator (increased anharmonicity)",
     "defaults": {"resonator_length_um": 4000, "junction_ic_nA": 30, "target_freq_GHz": 5.0,
                  "anharmonicity_MHz": -300, "material": "Niobium", "layer": 1}},

    # ── Resonators (more) ──
    {"id": "lumped-lc-resonator", "kind": "resonator", "name": "Lumped-Element LC Resonator", "category": "Resonators", "color": "cyan",
     "description": "Compact interdigitated-capacitor + meander-inductor resonator",
     "defaults": {"inductance_nH": 2.0, "capacitance_fF": 250, "frequency_GHz": 7.1, "coupling_MHz": 1.5}},

    # ── Couplers / junctions (more) — Qiskit Metal jj_dolan / jj_manhattan / SQUID_LOOP, SQuADDS claw ──
    {"id": "claw", "kind": "coupler", "name": "Claw Coupling Pad", "category": "Couplers", "color": "violet",
     "description": "CPW claw that capacitively couples a qubit to its readout resonator",
     "defaults": {"claw_length_um": 130, "claw_width_um": 15, "claw_gap_um": 6, "ground_spacing_um": 10}},
    {"id": "jj-dolan", "kind": "junction", "name": "Josephson Junction (Dolan)", "category": "Couplers", "color": "warning",
     "description": "Single Dolan-bridge (shadow-evaporated) Josephson junction",
     "defaults": {"junction_area_um2": 0.03, "ic_nA": 30, "bridge_width_nm": 200, "undercut_nm": 400, "layers": 2}},
    {"id": "jj-manhattan", "kind": "junction", "name": "Josephson Junction (Manhattan)", "category": "Couplers", "color": "warning",
     "description": "Single Manhattan-style (bridge-free, crossed-wire) Josephson junction",
     "defaults": {"junction_area_um2": 0.03, "ic_nA": 30, "wire_width_nm": 150, "layers": 2}},
    {"id": "squid-loop", "kind": "squid", "name": "SQUID Loop", "category": "Couplers", "color": "violet",
     "description": "Flux-tunable two-junction loop used inside tunable qubits/couplers",
     "defaults": {"loop_area_um2": 50, "junction_area_um2": 0.03, "junction_asymmetry": 0.0, "ic_nA": 30}},

    # ── Control (more) ──
    {"id": "charge-line", "kind": "flux-line", "name": "Charge / Gate Line", "category": "Control", "color": "warning",
     "description": "DC/gate bias line (gatemon gate, charge offset control)",
     "defaults": {"voltage_V": 0.0, "width_um": 6, "gap_um": 4, "distance_um": 10}},
    {"id": "bias-tee", "kind": "feedline", "name": "Bias Tee", "category": "Control", "color": "warning",
     "description": "On-chip DC+RF combiner (flux bias + fast pulse on one line)",
     "defaults": {"dc_block_nF": 10, "rf_cutoff_MHz": 80, "impedance_ohm": 50}},

    # ── Readout & amplification (more) — circulator (PRX 7,041043), pump filter (arXiv:2505.02740) ──
    {"id": "circulator", "kind": "parametric-amplifier", "name": "On-Chip Circulator / Isolator", "category": "Readout", "color": "success",
     "description": "Non-reciprocal element routing signal away from the qubit (magnet-free)",
     "defaults": {"center_freq_GHz": 7.0, "bandwidth_MHz": 200, "isolation_dB": 20, "insertion_loss_dB": 1}},
    {"id": "pump-filter", "kind": "purcell-filter", "name": "Pump-Port Filter", "category": "Readout", "color": "cyan",
     "description": "Band-pass filter on a parametric-amplifier pump port (>60 dB rejection)",
     "defaults": {"passband_GHz": 7.0, "bandwidth_GHz": 2.0, "rejection_dB": 60}},

    # ── Packaging & 3D integration (more) — gdsfactory QPDK Flipmon ──
    {"id": "flip-chip-bump", "kind": "tsv", "name": "Flip-Chip Bump Bond", "category": "Chip", "color": "success",
     "description": "Indium bump bond joining qubit chip to a carrier chip (flip-chip)",
     "defaults": {"diameter_um": 20, "height_um": 10, "pitch_um": 100, "material": "Indium"}},
    {"id": "interposer", "kind": "ground", "name": "Interposer", "category": "Chip", "color": "success",
     "description": "Carrier/routing chip bonded beneath the qubit chip in a flip-chip stack",
     "defaults": {"length_mm": 10, "width_mm": 10, "thickness_um": 525, "material": "Silicon"}},
    {"id": "flux-trap-holes", "kind": "ground", "name": "Flux-Trapping Holes", "category": "Chip", "color": "success",
     "description": "Ground-plane hole array that pins magnetic vortices (flux trapping)",
     "defaults": {"hole_size_um": 2, "pitch_um": 10, "layer": 0}},

    # ── Filters & amplification (completeness pass) ──
    {"id": "bandpass-filter", "kind": "purcell-filter", "name": "Bandpass Filter", "category": "Resonators", "color": "cyan",
     "description": "CPW bandpass filter for the readout / measurement chain",
     "defaults": {"center_freq_GHz": 7.0, "bandwidth_MHz": 300, "order": 2, "impedance_ohm": 50}},
    {"id": "notch-filter", "kind": "purcell-filter", "name": "Notch / Band-Stop Filter", "category": "Resonators", "color": "cyan",
     "description": "Band-stop filter rejecting a narrow band (e.g. pump leakage)",
     "defaults": {"reject_freq_GHz": 12.0, "bandwidth_MHz": 200, "rejection_dB": 40}},
    {"id": "kit-amplifier", "kind": "parametric-amplifier", "name": "Kinetic-Inductance / SLUG Amplifier", "category": "Readout", "color": "success",
     "description": "Near-quantum-limited first-stage amplifier (KIT / SLUG)",
     "defaults": {"gain_dB": 20, "bandwidth_GHz": 2.0, "noise_K": 0.3, "center_freq_GHz": 7.0}},
    {"id": "directional-coupler", "kind": "coupler", "name": "Directional Coupler", "category": "Readout", "color": "success",
     "description": "Injects the pump / taps the signal on an amplifier or readout line",
     "defaults": {"coupling_dB": -20, "directivity_dB": 25, "center_freq_GHz": 7.0}},
    {"id": "through-substrate-coax", "kind": "tsv", "name": "Through-Substrate Coax", "category": "Chip", "color": "success",
     "description": "Vertical coaxial interconnect through the wafer for 3D signal routing",
     "defaults": {"diameter_um": 60, "depth_um": 525, "impedance_ohm": 50, "material": "Copper"}},
]

# Superconducting films. `surface_tanD` is the representative metal–air interface
# loss tangent the film tends to give (TLS-dominated); `best_t1_us` is a published
# best-case transmon T1 associated with that film (a "what's achievable" marker, not
# a guarantee). Values are representative literature figures — see `refs`.
CONDUCTORS = [
    {"id": "al", "name": "Aluminum", "conductivity_Sm": 3.8e7, "tcK": 1.2, "rho_n_uohm_cm": 2.7,
     "surface_tanD": 1.5e-3, "best_t1_us": 100, "refs": ["Barends 2013", "Krantz 2019"],
     "note": "Junction electrodes; the original transmon film"},
    {"id": "nb", "name": "Niobium", "conductivity_Sm": 6.6e6, "tcK": 9.3, "rho_n_uohm_cm": 15.0,
     "surface_tanD": 2.0e-3, "best_t1_us": 80, "refs": ["IBM", "Krantz 2019"],
     "note": "Workhorse film; higher Tc, larger native-oxide loss"},
    {"id": "tin", "name": "Titanium Nitride", "conductivity_Sm": 5.0e6, "tcK": 4.5, "rho_n_uohm_cm": 100.0,
     "surface_tanD": 1.0e-3, "best_t1_us": 60, "refs": ["Vissers 2010", "Ohya 2014"],
     "note": "High kinetic inductance; low surface loss"},
    {"id": "nbn", "name": "Niobium Nitride", "conductivity_Sm": 2.5e6, "tcK": 16.0, "rho_n_uohm_cm": 200.0,
     "surface_tanD": 2.0e-3, "best_t1_us": 30, "refs": ["Niepce 2019"],
     "note": "Very high Lk, high Tc"},
    {"id": "nbtin", "name": "Niobium Titanium Nitride", "conductivity_Sm": 3.0e6, "tcK": 14.5, "rho_n_uohm_cm": 150.0,
     "surface_tanD": 1.2e-3, "best_t1_us": 50, "refs": ["Bruno 2015"],
     "note": "High-Lk, low-loss"},
    {"id": "granal", "name": "Granular Aluminum", "conductivity_Sm": 1.0e5, "tcK": 1.8, "rho_n_uohm_cm": 800.0,
     "surface_tanD": 2.0e-3, "best_t1_us": 30, "refs": ["Grünhaupt 2019", "Maleeva 2018"],
     "note": "Superinductor films (kΩ/sq sheet Lk)"},
    {"id": "ta", "name": "Tantalum", "conductivity_Sm": 7.7e6, "tcK": 4.4, "rho_n_uohm_cm": 13.0,
     "surface_tanD": 5.0e-4, "best_t1_us": 500, "refs": ["Place 2021", "Wang 2022"],
     "note": "Record coherence (α-Ta on sapphire, T1 ~0.3–0.5 ms)"},
    {"id": "au", "name": "Gold", "conductivity_Sm": 4.1e7, "tcK": 0, "rho_n_uohm_cm": 2.2,
     "surface_tanD": None, "best_t1_us": None, "refs": [],
     "note": "Normal-metal wirebond / GND (not superconducting)"},
    {"id": "cu", "name": "Copper", "conductivity_Sm": 5.96e7, "tcK": 0, "rho_n_uohm_cm": 1.7,
     "surface_tanD": None, "best_t1_us": None, "refs": [],
     "note": "Normal-metal packaging (not superconducting)"},
]

# Substrates. `thermal_W_mK` is the ~room-temperature thermal conductivity (cryogenic
# values differ but the ranking holds); `tanD` is the bulk dielectric loss tangent.
SUBSTRATES = [
    {"id": "si", "name": "Silicon", "eps": 11.7, "tanD": 2e-7, "thickness_um": 525,
     "thermal_W_mK": 150, "best_t1_us": 270, "refs": ["Krantz 2019"],
     "note": "High-resistivity Si; foundry-standard"},
    {"id": "sapphire", "name": "Sapphire", "eps": 9.8, "tanD": 1e-7, "thickness_um": 430,
     "thermal_W_mK": 35, "best_t1_us": 500, "refs": ["Place 2021"],
     "note": "Low-loss c-plane; best with α-Ta"},
    {"id": "sic", "name": "Silicon Carbide", "eps": 9.7, "tanD": 5e-7, "thickness_um": 500,
     "thermal_W_mK": 490, "best_t1_us": 60, "refs": ["Lukashenko 2022"],
     "note": "Very high thermal conductivity"},
    {"id": "quartz", "name": "Quartz", "eps": 3.8, "tanD": 3e-7, "thickness_um": 500,
     "thermal_W_mK": 10, "best_t1_us": 50, "refs": [],
     "note": "Fused silica; low εr → larger features"},
]

LOSS_INTERFACES = [
    {"id": "MA", "name": "Metal-Air", "p": 6e-5, "tanD": 1.5e-3},
    {"id": "SA", "name": "Substrate-Air", "p": 9e-5, "tanD": 2.2e-3},
    {"id": "MS", "name": "Metal-Substrate", "p": 3e-5, "tanD": 2.6e-3},
    {"id": "bulk", "name": "Bulk dielectric", "p": 0.9, "tanD": 1.8e-7},
]

DRC_RULES = [
    {"id": "gap", "name": "Min CPW gap", "value": 6, "min": 4, "unit": "um"},
    {"id": "width", "name": "Min trace width", "value": 10, "min": 4, "unit": "um"},
    {"id": "jj", "name": "Junction overlap", "value": 0.045, "min": 0.02, "max": 0.09, "unit": "um2"},
    {"id": "spacing", "name": "Qubit spacing", "value": 1200, "min": 800, "unit": "um"},
    {"id": "airbridge", "name": "Airbridge span", "value": 30, "min": 10, "max": 60, "unit": "um"},
    {"id": "keepout", "name": "Dicing keep-out", "value": 200, "min": 150, "unit": "um"},
    {"id": "metal_density", "name": "Metal fill density", "value": 0.45, "min": 0.2, "max": 0.8, "unit": "ratio"},
    {"id": "min_feature", "name": "Min feature size", "value": 2, "min": 1, "unit": "um"},
    {"id": "bondpad", "name": "Wirebond pad size", "value": 300, "min": 100, "unit": "um"},
    {"id": "layer_overlap", "name": "Inter-layer overlap", "value": 3, "min": 1, "unit": "um"},
    {"id": "etch_bias", "name": "Etch bias compensation", "value": 0.1, "min": 0.0, "max": 0.5, "unit": "um"},
]

# Fabrication process recipes — each step with the tolerance that drives yield.
PROCESS_RECIPES = [
    {"id": "nb-trilayer", "name": "Nb Trilayer (foundry)", "substrate": "si", "metal": "nb",
     "steps": [
         {"name": "Wafer clean (RCA/HF)", "tolerance_nm": 0, "purpose": "remove native oxide & organics"},
         {"name": "Nb sputter deposition", "tolerance_nm": 5, "purpose": "200 nm base electrode"},
         {"name": "Optical lithography", "tolerance_nm": 200, "purpose": "define CPW / pads"},
         {"name": "Reactive-ion etch (SF6)", "tolerance_nm": 15, "purpose": "pattern transfer + etch bias"},
         {"name": "Junction e-beam + double-angle Al", "tolerance_pct": 3.0, "purpose": "Manhattan junctions"},
         {"name": "Bandage / airbridge", "tolerance_nm": 10, "purpose": "galvanic contact + crossovers"},
         {"name": "Dice & package", "tolerance_nm": 0, "purpose": "singulate, wirebond"},
     ]},
    {"id": "ta-sapphire", "name": "Ta on Sapphire (high-coherence)", "substrate": "sapphire", "metal": "ta",
     "steps": [
         {"name": "Sapphire anneal", "tolerance_nm": 0, "purpose": "smooth surface"},
         {"name": "Ta sputter @ high T (α-phase)", "tolerance_nm": 4, "purpose": "low-loss bcc Ta"},
         {"name": "Optical lithography", "tolerance_nm": 200, "purpose": "define geometry"},
         {"name": "Wet/dry etch + piranha clean", "tolerance_nm": 12, "purpose": "low surface TLS"},
         {"name": "Al/AlOx junctions", "tolerance_pct": 3.0, "purpose": "Dolan/Manhattan"},
     ]},
    {"id": "tin-hi-lk", "name": "TiN High-Lₖ", "substrate": "si", "metal": "tin",
     "steps": [
         {"name": "ALD/sputter TiN", "tolerance_nm": 3, "purpose": "tune Tc / sheet Lk"},
         {"name": "Lithography + etch", "tolerance_nm": 12, "purpose": "high-impedance lines"},
         {"name": "Al junctions", "tolerance_pct": 4.0, "purpose": "qubit junctions"},
     ]},
]

# Parameter specifications — unit / range / typical, for UI inputs & validation.
PARAMETER_SPECS = {
    "target_freq_GHz": {"unit": "GHz", "min": 0.1, "max": 12.0, "typical": 5.0, "group": "qubit"},
    "anharmonicity_MHz": {"unit": "MHz", "min": -400, "max": -150, "typical": -310, "group": "qubit"},
    "c_sigma_fF": {"unit": "fF", "min": 40, "max": 130, "typical": 80, "group": "qubit"},
    "ic_nA": {"unit": "nA", "min": 5, "max": 60, "typical": 30, "group": "junction"},
    "junction_width_nm": {"unit": "nm", "min": 100, "max": 400, "typical": 200, "group": "junction"},
    "pad_gap_um": {"unit": "µm", "min": 4, "max": 60, "typical": 30, "group": "geometry"},
    "pad_width_um": {"unit": "µm", "min": 100, "max": 700, "typical": 455, "group": "geometry"},
    "fillet_radius_um": {"unit": "µm", "min": 2, "max": 120, "typical": 10, "group": "geometry"},
    "length_um": {"unit": "µm", "min": 500, "max": 12000, "typical": 4200, "group": "resonator"},
    "impedance_ohm": {"unit": "Ω", "min": 30, "max": 120, "typical": 50, "group": "resonator"},
    "kappa_MHz": {"unit": "MHz", "min": 0.1, "max": 10, "typical": 1.2, "group": "readout"},
    "coupling_MHz": {"unit": "MHz", "min": 10, "max": 300, "typical": 92, "group": "coupling"},
    "thickness_nm": {"unit": "nm", "min": 20, "max": 400, "typical": 100, "group": "film"},
    "junction_tolerance_pct": {"unit": "%", "min": 0.5, "max": 8.0, "typical": 3.0, "group": "fabrication"},
    "spec_window_MHz": {"unit": "MHz", "min": 5, "max": 100, "typical": 15, "group": "fabrication"},
}

# Validated reference designs (SQuADDS-style): known-good parameter sets with
# measured-vs-simulated values, usable as fab-ready starting points. Mirrors the
# role of the SQuADDS database (LFL-Lab); can be wired to the live HF dataset later.
VALIDATED_DESIGNS = [
    {"id": "sq-xmon-5ghz", "name": "Xmon 5.0 GHz", "qubit": "transmon",
     "target_freq_GHz": 5.0, "anharmonicity_MHz": -270,
     "params": {"pad_width_um": 455, "pad_height_um": 90, "pad_gap_um": 30,
                "c_sigma_fF": 85, "ic_nA": 28, "material": "Tantalum"},
     "validated": {"measured_f01_GHz": 4.98, "measured_T1_us": 95, "yield_pct": 72},
     "source": "SQuADDS-style reference (Ta/sapphire)"},
    {"id": "sq-transmon-4_5ghz", "name": "Transmon 4.5 GHz (low-noise)", "qubit": "transmon",
     "target_freq_GHz": 4.5, "anharmonicity_MHz": -240,
     "params": {"pad_width_um": 500, "pad_height_um": 100, "pad_gap_um": 40,
                "c_sigma_fF": 95, "ic_nA": 24, "material": "Tantalum"},
     "validated": {"measured_f01_GHz": 4.47, "measured_T1_us": 120, "yield_pct": 80},
     "source": "SQuADDS-style reference (large pads, low surface loss)"},
    {"id": "sq-transmon-6ghz", "name": "Transmon 6.0 GHz (fast readout)", "qubit": "transmon",
     "target_freq_GHz": 6.0, "anharmonicity_MHz": -300,
     "params": {"pad_width_um": 420, "pad_height_um": 80, "pad_gap_um": 25,
                "c_sigma_fF": 72, "ic_nA": 34, "material": "Niobium"},
     "validated": {"measured_f01_GHz": 5.96, "measured_T1_us": 60, "yield_pct": 65},
     "source": "SQuADDS-style reference (compact, higher freq)"},
    {"id": "sq-fluxonium-0_5ghz", "name": "Fluxonium 0.5 GHz", "qubit": "fluxonium",
     "target_freq_GHz": 0.5, "anharmonicity_MHz": 1200,
     "params": {"EJ_GHz": 4.0, "EC_GHz": 1.0, "EL_GHz": 0.9, "junction_count": 100},
     "validated": {"measured_f01_GHz": 0.52, "measured_T1_us": 320, "yield_pct": 55},
     "source": "SQuADDS-style reference (high-coherence fluxonium)"},
]
